name: Run unit tests
on: 
  workflow_call:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Install dependencies
        run: go mod tidy

      - name: Finally run the unit tests
        run: go test ./... -v
        